### ISSUE TITLE
Annual Summary table not updating

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#110]
Hi @Gary-van-Breda @DavidRoy 

It seems that the Annual Summary Table is not keeping up-to-date. 
The Raw Data tables are fine, but Summary Table and Estimates Table are showing absolutely nothing for Week 5 (29th April onwards), implying that no data have fed through to these tables since at least Monday.

Can someone please take a look?

Thanks,

Ian

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : can you remind me which bits we've switched off?

**Comment by Gary-van-Breda** [comment]
@johnvanbreda : can you remind me which bits we've switched off for performance reasons?

**Comment by johnvanbreda** [comment]
It was disabled due to the server problems last week. As they are now resolved, I've re-enabled it but left check_deleted_locations and lines 330 to 358 commented out as previously suggested.

**Comment by IanMiddlebrook** [comment]
@DavidRoy @Gary-van-Breda @johnvanbreda @BirenRathod

Hi, is there anyone that can take a look at this issue please - the Summary Table is still not updating, at least 10 days behind data entry?

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Summary builder was switched into catch up mode for Transects, and both WCBS.
Data on Annual summary now looks up to date.
Summary builder has been switched back to normal mode.

**Comment by DavidRoy** [comment]
Closing as the background processing has caught up
