### ISSUE TITLE
order of species on data entry page

### ISSUE THREAD

**Issue by IanMiddlebrook** [BiologicalRecordsCentre/UKBMS-online#247]
Hi @DavidRoy 
I'm not sure when this happened, or if it's always been this way, but the order of species in the online data entry form does not match the standard field recording forms. Specifically, the field recording forms go Meadow Brown, Ringlet, Small Heath, whereas the online form goes Meadow Brown, Small Heath, Ringlet.
This can/will lead to data transcription errors.

I remember, many years ago, the field recording form was re-designed to match the order in the old Transect Walker software, which followed the new taxonomic order of the day, but I'm not sure why the online order has gone back the other way round.

Is this something that can be easily changed?

I know taxonomic order is completely different now, but we agreed not to keep changing the field forms, so it would make sense for the online form to match.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook

I've included here a list of all the species in the Butterfly list. The Meadow Brown/Small Heath/Ringlet are at the end. Changing this order is just simply changing the value of the taxonomic_sort order, and is quite easy. However, the Large Heath is in amongst them - what should the order be when we include the Large Heath?  
  
There are 2 other cases we need to consider, as they feature duplicated taxonomic sort orders, and sorting this now seems a sensible thing to do - otherwise we can't guarantee the order.  

- Sort order 11: Leptidea juvernica (Cryptic Wood White) and Leptidea sinapis (Wood White)  
- Sort order 65: Danaus plexippus (Monarch) and Pararge aegeria (Speckled Wood)

Several of the taxa do not have a rank: can you confirm what these are? I'll also update those.  
  
I've included a couple of columns showing whether the taxa are included in the existing common list, and the new common list proposed in #223  
  
id | parent_id | sort order | taxon | common_name | taxon_rank | Original Common | New Common
-- | -- | -- | -- | -- | -- | -- | --
283020 | 283012 | 1 | Carterocephalus palaemon | Chequered Skipper | Species |   |  
283022 | 283012 | 2 | Thymelicus sylvestris | Small Skipper | Species |   |  
283024 | 283012 | 3 | Thymelicus lineola | Essex Skipper | Species |   |  
283018 | 283012 | 4 | Small/Essex Skipper | Small/Essex Skipper |   |   |  
283026 | 283012 | 5 | Thymelicus acteon | Lulworth Skipper | Species |   |  
283028 | 283012 | 6 | Hesperia comma | Silver-spotted Skipper | Species |   |  
283030 | 283012 | 7 | Ochlodes sylvanus | Large Skipper |   |   |  
283032 | 283012 | 8 | Erynnis tages | Dingy Skipper | Subspecies |  
283034 | 283012 | 9 | Pyrgus malvae | Grizzled Skipper | Species |   |  
283036 | 283013 | 10 | Papilio machaon | Swallowtail | Species |   |  
316475 | 283014 | 11 | Leptidea juvernica | Cryptic Wood White |   |   |  
283038 | 283014 | 11 | Leptidea sinapis | Wood White | Species |   |  
283040 | 283014 | 12 | Colias hyale | Pale Clouded Yellow | Species |   |  
283042 | 283014 | 14 | Colias alfacariensis | Berger's Clouded Yellow | Species |   |  
283044 | 283014 | 15 | Colias croceus | Clouded Yellow | Species |   |  
283046 | 283014 | 16 | Gonepteryx rhamni | Brimstone | Species | Y | Y
283048 | 283014 | 18 | Pieris brassicae | Large White | Species | Y | Y
283050 | 283014 | 19 | Pieris rapae | Small White | Species |   | Y
283052 | 283014 | 20 | Pieris napi | Green-veined White | Species |   | Y
283054 | 283014 | 22 | Anthocharis cardamines | Orange Tip | Species | Y | Y
283056 | 283015 | 23 | Callophrys rubi | Green Hairstreak | Species |   |  
283058 | 283015 | 24 | Thecla betulae | Brown Hairstreak | Species |   |  
283060 | 283015 | 25 | Neozephrus (Quercusia) quercus | Purple Hairstreak | Species |   |  
283062 | 283015 | 26 | Satyrium w-album | White-letter Hairstreak | Species |   |  
283064 | 283015 | 27 | Satyrium pruni | Black Hairstreak | Species |   |  
283066 | 283015 | 28 | Lycaena phlaeas | Small Copper | Species | Y | Y
283068 | 283015 | 29 | Lycaena dispar | Large Copper |   |   |  
283070 | 283015 | 32 | Cupido minimus | Small Blue | Species |   |  
283072 | 283015 | 34 | Plebeius (Plebejus) argus | Silver-studded Blue | Species |   |  
283074 | 283015 | 35 | Aricia agestis | Brown Argus | Species |   |  
283076 | 283015 | 36 | Aricia artaxerxes | Northern Brown Argus | Species |   |  
283078 | 283015 | 37 | Polyommatus icarus | Common Blue | Species | Y | Y
283080 | 283015 | 39 | Polyommatus (Lysandra) coridon | Chalk-hill Blue |   |   |  
283082 | 283015 | 40 | Polyommatus (Lysandra) bellargus | Adonis Blue |   |   |  
283084 | 283015 | 42 | Celastrina argiolus | Holly Blue | Species |   | Y
284500 | 283015 | 43 | Phengaris arion | Large Blue | Species |   |  
283086 | 283016 | 45 | Hamearis lucina | Duke of Burgundy Fritillary | Species |   |  
283088 | 283016 | 46 | Limenitis camilla | White Admiral | Species |   |  
283090 | 283016 | 47 | Apatura iris | Purple Emperor | Species |   |  
283092 | 283016 | 48 | Vanessa atalanta | Red Admiral | Species | Y | Y
283094 | 283016 | 49 | Vanessa (Cynthia) cardui | Painted Lady | Species | Y | Y
283096 | 283016 | 50 | Aglais urticae | Small Tortoiseshell | Species |   | Y
283098 | 283016 | 51 | Nymphalis polychloros | Large Tortoiseshell |   |   |  
283100 | 283016 | 52 | Nymphalis antiopa | Camberwell Beauty | Species |   |  
283102 | 283016 | 53 | Inachis io | Peacock | Species | Y | Y
283104 | 283016 | 54 | Polygonia c-album | Comma | Species |   | Y
283106 | 283016 | 56 | Boloria selene | Small Pearl-bordered Fritillary | Species |   |  
283108 | 283016 | 57 | Boloria euphrosyne | Pearl-bordered Fritillary | Species |   |  
283110 | 283016 | 59 | Argynnis adippe | High Brown Fritillary | Species |   |  
283112 | 283016 | 60 | Argynnis aglaja | Dark Green Fritillary | Species |   |  
283114 | 283016 | 61 | Argynnis paphia | Silver-washed Fritillary | Species |   |  
283116 | 283016 | 62 | Euphydryas (Eurodryas) aurinia | Marsh Fritillary | Species |   |  
283118 | 283016 | 63 | Melitaea cinxia | Glanville Fritillary | Species |   |  
283120 | 283016 | 64 | Melitaea (Mellicta) athalia | Heath Fritillary | Species |   |  
431521 | 283016 | 65 | Danaus plexippus | Monarch | Species |   |  
283122 | 283017 | 65 | Pararge aegeria | Speckled Wood | Species | Y | Y
283124 | 283017 | 66 | Lasiommata megera | Wall Brown | Species |   |  
283126 | 283017 | 67 | Erebia epiphron | Mountain Ringlet | Species |   |  
283128 | 283017 | 68 | Erebia aethiops | Scotch Argus | Species |   |  
283130 | 283017 | 69 | Melanargia galathea | Marbled White | Species |   | Y
283132 | 283017 | 70 | Hipparchia semele | Grayling | Species |   |  
283134 | 283017 | 71 | Pyronia tithonus | Gatekeeper / Hedge Brown | Species | Y | Y
283136 | 283017 | 72 | Maniola jurtina | Meadow Brown | Species | Y | Y
283138 | 283017 | 73 | Coenonympha pamphilus | Small Heath | Species |   | Y
283140 | 283017 | 74 | Coenonympha tullia | Large Heath | Species |   |  
283142 | 283017 | 75 | Aphantopus hyperantus | Ringlet | Species | Y | Y



</body>

</html>

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda @DavidRoy 

For the bottom of the list, I've checked with recording forms and old Transect Walker software, and they all have Ringlet sitting between Meadow Brown and Small Heath - so that would be the best order for recorders.

For the Cryptic/Wood White, we don't have a precedent, and modern taxonomy places Cryptic Wood White after Wood White, so we'll go with that.

Monarch should be above Speckled Wood - however this brings me to another point:

Pale Clouded Yellow, Berger's Clouded Yellow, Large Copper, Large Tortoiseshell, Camberwell Beauty, Monarch - these are all rare migrants, which the UKBMS does not report on. Most records of these are entered by mistake or need to be verified. The mistakes could be avoided if they were not on the 'full' list. Would it be possible to remove them from the 'full' list, but keep them (along with Queen of Spain Fritillary) available to add to your site list (deliberately) if you had a genuine record?
Queen of Spain Fritillary is a request from the Channel Isles, which sees it fairly regularly.

As for taxon-rank - I would've thought they were all Species - I'm not sure why Dingy Skipper is considered a different case? I'd need to defer to @DavidRoy on this point.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook @DavidRoy 
I've altered the ordering as follows:

- Wood White is now before Cryptic Wood White
- Monarch is now before Speckled Wood
- Ringlet is now between Meadow Brown and Small Heath (Large Heath is at the very end)

The code currently does not allow for the "full" list to be a subset of the species on the list: we could do something similar to the common species list, and have it driven off a Yes/No attribute on the taxon. @DavidRoy : shall I do this?

**Comment by IanMiddlebrook** [comment]
Instead of calling it the Full list, if we remove the rare migrants by default, could we call it 'All UK Regulars' ?

**Comment by IanMiddlebrook** [comment]
Hi @DavidRoy  @Gary-van-Breda , 
the remaining issue of rare migrants has raised its head again this season, with Queen of Spain Fritillary and Long-tailed Blue being recorded on transects, but the recorders unable to enter those records on the butterfly list.

I think the preferred/workable solution is that we extend the available migrants on the 'full' list to include both these species, but we add a list of 'All UK Regulars' which does not include the rare migrants, so can be used to avoid errors in the majority of circumstances.

Thanks, Ian

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook @DavidRoy 
Which of the **existing** species on the Butterflies list are rare migrants (i.e. those which we do not want on the Regulars list)?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

Pale Clouded Yellow
Berger's Clouded Yellow
Large Copper
Large Tortoiseshell
Camberwell Beauty
Monarch

**Comment by Gary-van-Breda** [comment]
Hi @IanMiddlebrook : I've pushed a change for the extra "All UK Regulars" species preload list to the Test environment, and configured it on the normal Transect walk data entry (not WCBS yet). Could you check you are happy?

**Comment by IanMiddlebrook** [comment]
Hi @Gary-van-Breda 

The UK Regulars list looks fine

The 'All' list is still missing those additional rare migrants mentioned in my comment from August 2022 - Queen of Spain Fritillary, Long-tailed Blue

I think Long-tailed Blue would need to be between Large Copper and Small Blue
Queen of Spain Fritillary, between Pearl-bordered Fritillary and High Brown Fritillary

Thanks, Ian

**Comment by Gary-van-Breda-EdiUni** [comment]
@DavidRoy : Is there someone who is responsible for the upkeep of the species list for UKBMS? (has it been uploaded from some reference source?), Or are you happy for me to add these at the position's Ian has mentioned?

**Comment by DavidRoy** [comment]
@Gary-van-Breda happy to go with Ian's advice on this

**Comment by Gary-van-Breda** [comment]
@IanMiddlebrook : I have added the two taxa in the requested positions.
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/621050
https://warehouse1.indicia.org.uk/index.php/taxa_taxon_list/edit/621052

To be honest, I don't know which keys are important in this case - do you know?

**Comment by IanMiddlebrook** [comment]
Sorry @Gary-van-Breda , I don't have permission to access those links, but I doubt I'd know which keys were important. Perhaps one for @DavidRoy to check?
