### ISSUE TITLE
Issue entering new species

### ISSUE THREAD

**Issue by marcbotham** [BiologicalRecordsCentre/UKBMS-online#260]
When trying to add a new species of moth to my list that I haven't recorded before or hasn't been recorded on the site, I type the species but the drop down menu doesn't appear and the spinning wheel just persists until I either leave the entry or close the page. So at the moment I cannot add data for species not already on my lists

**Comment by Gary-van-Breda** [comment]
@marcbotham (@IanMiddlebrook @DavidRoy )
Fix deployed to test for review.

**Comment by marcbotham** [comment]
I just tried this and I'm still not getting a drop down menu when I type a new species name in. I just get the spinning wheel and nothing happens no matter how long I leave it

**Comment by Gary-van-Breda** [comment]
@marcbotham When I masquerade as you into the test system it works OK for me. Can you make sure you clear your browser cache, then try again? Thanks.

**Comment by Gary-van-Breda** [comment]
@marcbotham : this has only been deployed to the test site so far.

**Comment by marcbotham** [comment]
works for me on test site, thank you

**Comment by Gary-van-Breda** [comment]
Deployed to Live. Checked.
Closing
